### PR TITLE
updated go ethereum version to `v1.12.0` and updated circleci config go version

### PR DESCRIPTION
**Pull request by Yashk767**
- Pre requisite for go ethereum `v1.12.0`, is go `1.19` so updated the latest go version `1.21.1` as well.
- Updated go-ethereum version to `1.12.0`.
- Updated all the dependencies according to `go1.21.1`.
- Ran `go mod tidy`
- updated go1.21.1 and go ethereum version 1.12.0 for circleci config
- updated go version pre requisite in ReadMe file. 

Part of issue fixing #1085

### CODE REVIEW

**Comment by Yashk767** [comment]
`go ethereum v1.12.0` requires at least `go 1.19`, so should we keep `go1.19` or latest `go1.21.1` version in our `go.mod`  file here https://github.com/razor-network/oracle-node/pull/1117/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L3 @SkandaBhat @ashish10677

**Comment by Yashk767** [comment]
> `go ethereum v1.12.0` requires at least `go 1.19`, so should we keep `go1.19` or latest `go1.21.1` version in our `go.mod` file here https://github.com/razor-network/oracle-node/pull/1117/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L3 @SkandaBhat @ashish10677

If the existing staker is building node from source, there are high chances that they might not have latest `go1.21` so they need to update the go version to the latest to run `go.mod` but most of them would have `go1.19` so should we keep the later one in go.mod ?

**Comment by ashish10677** [comment]
> > `go ethereum v1.12.0` requires at least `go 1.19`, so should we keep `go1.19` or latest `go1.21.1` version in our `go.mod` file here https://github.com/razor-network/oracle-node/pull/1117/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L3 @SkandaBhat @ashish10677
> 
> If the existing staker is building node from source, there are high chances that they might not have latest `go1.21` so they need to update the go version to the latest to run `go.mod` but most of them would have `go1.19` so should we keep the later one in go.mod ?

Yeah but then in a few months we will have to upgrade again as go 1.19 will become very old. Let's update to the latest one

**Comment by Yashk767** [comment]
Ready for review @ashish10677

**Review by ashish10677 — APPROVED** [review]

**Pull request merged**
