### PR TITLE
Rebase `releases/v1.0.7` with `develop` branch

### PR DESCRIPTION
**Pull request by Yashk767**
# Problem Statement
`releases/v1.0.7` doesn't have updated commits from `develop` branch.

Closes https://linear.app/interstellar-research/issue/RAZ-467

# Solution
Merged `develop` into `releases/v1.0.7` and resolved conflicts

### CODE REVIEW

**Review by yohanelly95 — APPROVED** [review]

**Review by ashish10677 — APPROVED** [review]

**Comment by ashish10677** [comment]
I don't think it can be merged @Yashk767 because one commit isn't signed

**Comment by Yashk767** [comment]
> I don't think it can be merged @Yashk767 because one commit isn't signed

This is merging to `releases/v1.0.7` branch, It can be merged right?

**Comment by ashish10677** [comment]
> > I don't think it can be merged @Yashk767 because one commit isn't signed
> 
> This is merging to `releases/v1.0.7` branch, It can be merged right?

I'm getting this:
image
If you can merge then go ahead.

**Comment by Yashk767** [comment]
> I don't think it can be merged @Yashk767 because one commit isn't signed

Oops yes, I am not unable to merge, I need to sign the previous commit right? need to force push correct?

**Comment by Yashk767** [comment]
Even after resigning my merge commit , it still says all commits should be signed.

Screenshot 2023-10-13 at 3 53 07 AM
I think this commit from `develop` branch is required to be signed. cc @ashish10677 @SkandaBhat

**Comment by Yashk767** [comment]
updated the base branch to `feature/v1.1.0` @yohanelly95 @ashish10677

**Pull request merged**
